### ISSUE TITLE
42 Simulation does not run multiple times

### ISSUE THREAD

**Issue by dmccomas** [OpenSatKit/OpenSatKit#10]
If the 42 simulation is run to completion it won't run again without restarting the VM.  If the 42 simulation is interrupted then the simulation can be restarted without restarting the VM.

**Comment by derricku** [comment]
Confirmed having the same issue. 
When forced to quit it shows an "Unexpected Text" log with repeating "Input sudo password" and "Incorrect password entered" messages. 
42 seems to expect the sudo password like usual but fails to open a terminal input to do so.

**Comment by dmccomas** [comment]
Version 2.0 changed the 42-cFS relationship.  42 is now started with a very long simulation time with the goal of not letting 42 terminate on its own. 42 should only be terminated with a disconnect command and there aren't any issues with restarting 42 after it is disconnected.
