### ISSUE TITLE
Housekeeping Telemetry packets are not populating

### ISSUE THREAD

**Issue by clxyder** [OpenSatKit/OpenSatKit#113]
After updating the cmd and tlm messages IDs in both the `fsw_msg_ids.rb` and `example_app_msgids.h`, the housekeeping telemetry packets are not populating correctly on the `cFS Command and Telemetry Server` window.

On the `Targets` tab, I scroll down to see EXAMPLE row, but I do not see the telemetry count increase.

I have tried creating a new app with both the cFE developer guide and sample app templates and I have not had any luck with either.

Command messages work just fine, but telemetry messages (I have only tried housekeeping messages) don't seem to work.

If I leave updated `EXAMPLE_HK_TLM_MID` to have the same value of `OSK_TEST_HK_TLM_MID`, i.e. `0x0FF0` everything works fine.

But I run into the issue that any new app I create all use the same TLM MID, so  it defeats the purpose of the housekeeping messages.

Anything I might be missing? Thanks again.

**Comment by dmccomas** [comment]
The telemetry output app called KIT_TO has a packet filter table. The
message needs to be added to [target]_osk_to_pkt_tbl.json where target is
cfsat or sundar. Most of the packet filters are to telemeter every packet
so you should be able to copy another entry and replace the message ID

Dave

**Comment by clxyder** [comment]
Thank you very much Dave, that solved my issue! 😄
