### ISSUE TITLE
Run Script -> Ops Example -> No Prompt?

### ISSUE THREAD

**Issue by eupharis** [OpenSatKit/OpenSatKit#30]
99% of the app working perfectly. Woohoo! Running on Ubuntu 18.04.

Found another hopefully little bug with running the Ops script:  

![image](https://user-images.githubusercontent.com/847862/78402345-41affa80-75af-11ea-8929-07ba6fd3ebab.png)

When I select it, it just freezes. Then when I force quit, this pops up: 

![image](https://user-images.githubusercontent.com/847862/78402300-2cd36700-75af-11ea-99f2-28f3a62927bc.png)

I think maybe just no terminal is popping up to take my password?

Maybe you can just add a spawn xfce4-terminal when this particular script runs like in some other spots?

```
spawn("xfce4-terminal --default-working-directory=""#{Osk::CFS_EXE_DIR}"" --execute sudo ./core-cpu1""")
```

**Comment by dmccomas** [comment]
If the cFS is not running when you start the simsat ops example a message box should be displayed stating the cFS will be started and a new terminal window should appear. It's the same script that is used to start the cFS that is used by the main window. 

Are you running everything locally?

**Comment by eupharis** [comment]
Yup, running everything locally!

Ok now everything is working great.

It looks like the cause was that sometimes I have some "extra" `./core-cpu1` processes that hang around after playing around with OpenSatKit for awhile, even after trying to hit `Stop CFS`.

![image](https://user-images.githubusercontent.com/847862/81752427-47c6b000-9466-11ea-8dbd-c2ea436605c8.png)

If I make sure those are all dead and then do a fresh `ruby Launcher` for cosmos, then the ops script works great! Thanks!

**Comment by dmccomas** [comment]
I changed the 'Stop cFS" so it usses an executive service command thinking
it's more graceful but I may go back to the old way that stops all
core-cpu1 processes.
