### ISSUE TITLE
Misspelling in GitHub description

### ISSUE THREAD

**Issue by fishilico** [OpenSatKit/OpenSatKit#33]
Hi,
On the front page of the project on GitHub (https://github.com/OpenSatKit/OpenSatKit), the description is:
```
Core Fligfht System (cFS) Application Developer's Kit https://opensatkit.github.io
```

There seem to be too many `F` in `Fligfht`. Is this intended?

**Comment by dmccomas** [comment]
It was a typo & I fixed it. Thanks.
