### ISSUE TITLE
Question about CM Tags

### ISSUE THREAD

**Issue by PeteBlanchard** [OpenSatKit/OpenSatKit#39]
Hello, I notice that there are notifications on the "https://opensatkit.github.io/" about releases, but I don't see any tags in your software.  How are you maintaining CM of what is in each version?  I see master has been updated fairly recently.

Thanks in advance.

Regards,

  Pete

**Comment by PeteBlanchard** [comment]
I think you need to run something like the following to get your (local) tags to the server:

```bash
  git push --tags
```

**Comment by dmccomas** [comment]
Thanks that did the trick! I also just tagged the current code as 2.2.1 since its just been patches since 2.2 0 although I now see I never tagged 2.2.0.  Moving forward I'll be more rigorous.
