### ISSUE TITLE
OpenSatKit ERRNO::ENOENT : No such file or directory

### ISSUE THREAD

**Issue by hgarcia101685** [OpenSatKit/OpenSatKit#75]
When trying to click on any of the buttons to open any of the guides or resources, I get the following error(screenshot provided)
ERRNO::ENOENT : No such file or directory

![image](https://user-images.githubusercontent.com/10132775/128971158-ac8b4cc5-ef68-484d-83ac-b7e2771df838.png)

**Comment by hgarcia101685** [comment]
Just solved my own issue, but will leave here in case it helps anyone else.  The evince(pdf display) package was missing on my ubuntu container, so running this fixed it for me:
`apt-get install evince`

**Comment by dmccomas** [comment]
This is dated 2015, but it states evince is the default ubuntu pdf viewer
https://help.ubuntu.com/community/Evince

I could add evince installation to the install script if needed.
Which version of Ubuntu are you using?

Thanks - Dave

**Comment by hgarcia101685** [comment]
root@2972273c7169:~/OpenSatKit-master/cosmos/outputs/logs# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
